/**
 * Algoritmos e estruturas de dados — preparação de entrevista, em JS/TS.
 *
 * A ordem da árvore é a ordem de estudo: fundamento → estrutura → algoritmo →
 * padrão de entrevista. Resolver problema antes de ter o fundamento é o que
 * faz gente decorar 150 soluções e não passar em nenhuma entrevista.
 *
 * O bloco de DSA tem 1h/semana hoje — é o gargalo do plano. Quando o CS50
 * terminar, as ~4h/semana dele deveriam vir para cá.
 */
import type { Trilha } from './types';

export const ALGORITMOS: Trilha = {
  id: 'dsa', t: 'Algoritmos e estruturas', tipos: ['dsa'], cor: '--chart-3', marco: 'job', fecha: false,
  nota: 'Não são 150 problemas: são ~18 padrões. O problema é o exercício; o padrão é o conteúdo.',
  filhos: [

  { id:'dsa.fund', t:'Fundamentos', nota:'Sem isto, todo o resto vira decoreba.', filhos:[

    { id:'dsa.fund.cx', t:'Complexidade', filhos:[
      { id:'dsa.fund.cx.not', t:'Notação assintótica: O, Ω, Θ', min:30,
        saber:['definir as três e dizer qual se usa em entrevista e por quê','ordenar 8 funções por crescimento'] },
      { id:'dsa.fund.cx.loop', t:'Analisar laços e laços aninhados', min:30, pre:['dsa.fund.cx.not'],
        saber:['dar a complexidade de 10 trechos com laços','reconhecer o laço que parece O(n²) e é O(n)'] },
      { id:'dsa.fund.cx.esp', t:'Complexidade de espaço', min:30, pre:['dsa.fund.cx.not'],
        nota:'Espaço auxiliar vs total — a pergunta de acompanhamento mais comum em entrevista.',
        saber:['separar espaço da entrada do espaço auxiliar','contar o espaço da pilha de recursão'] },
      { id:'dsa.fund.cx.rec', t:'Complexidade de recursão: árvore de recorrência', min:45, pre:['dsa.fund.cx.loop'],
        saber:['montar a árvore de merge sort e chegar em O(n log n)','resolver 3 recorrências desenhando a árvore'] },
      { id:'dsa.fund.cx.mest', t:'Teorema mestre', min:30, pre:['dsa.fund.cx.rec'],
        saber:['aplicar os 3 casos','saber quando ele NÃO se aplica'] },
      { id:'dsa.fund.cx.amort', t:'Análise amortizada', min:30, pre:['dsa.fund.cx.loop'],
        nota:'Por que push num array dinâmico é O(1) mesmo redobrando o array de vez em quando.',
        saber:['explicar o argumento do redobramento','distinguir amortizado de caso médio'] },
      { id:'dsa.fund.cx.caso', t:'Melhor, médio e pior caso', min:30, pre:['dsa.fund.cx.not'],
        saber:['dar os três para busca linear, quick sort e tabela hash'] },
    ]},

    { id:'dsa.fund.js', t:'O modelo do JavaScript', nota:'Você escolheu JS/TS. Ele mente sobre várias coisas que a entrevista cobra.', filhos:[
      { id:'dsa.fund.js.arr', t:'Arrays em JS não são arrays', min:30,
        nota:'São objetos com chaves numéricas; o motor otimiza quando pode, e desotimiza quando você fura o padrão.',
        saber:['explicar o custo real de shift/unshift vs push/pop','saber o que cria um array esparso e por que evitar'] },
      { id:'dsa.fund.js.sort', t:'sort() é lexicográfico por padrão', min:20,
        nota:'A armadilha nº1: [10,9,1].sort() devolve [1,10,9].',
        saber:['escrever o comparador numérico sem pensar','saber que o sort do V8 é estável'] },
      { id:'dsa.fund.js.num', t:'Números, precisão e inteiros de 32 bits', min:30,
        saber:['explicar por que 0.1+0.2 !== 0.3','saber que operadores bitwise truncam para 32 bits com sinal','usar BigInt quando estourar'] },
      { id:'dsa.fund.js.map', t:'Map vs Object vs Set', min:30,
        saber:['dizer quando Map ganha de Object','saber que Map preserva ordem de inserção e aceita qualquer chave'] },
      { id:'dsa.fund.js.str', t:'Strings imutáveis e custo de concatenação', min:20,
        saber:['saber por que concatenar em laço é O(n²) no pior caso','usar array + join no lugar'] },
      { id:'dsa.fund.js.ref', t:'Referência, cópia rasa e cópia profunda', min:20,
        saber:['prever quando uma mutação vaza para fora da função','copiar matriz sem alias de linha'] },
      { id:'dsa.fund.js.pilha', t:'Recursão e limite de pilha', min:20, pre:['dsa.fund.cx.rec'],
        nota:'JS não tem eliminação de chamada de cauda na prática. Recursão profunda estoura.',
        saber:['estimar a profundidade segura','converter uma recursão em iteração com pilha explícita'] },
      { id:'dsa.fund.js.kit', t:'Kit de estruturas que o JS não tem', min:60, pre:['dsa.fund.js.arr'],
        nota:'Sem heap, sem deque, sem union-find na biblioteca padrão. Em entrevista você escreve na hora — então escreva uma vez, bem, e memorize.',
        saber:['MinHeap/MaxHeap genérico com comparador','Deque O(1) nas duas pontas','UnionFind com compressão de caminho','TrieNode','tudo em TS, testado, decorado'] },
    ]},
  ]},

  { id:'dsa.ed', t:'Estruturas de dados', nota:'Cada uma: como funciona por dentro, custo de cada operação, quando é a escolha certa.', filhos:[

    { id:'dsa.ed.lin', t:'Lineares', filhos:[
      { id:'dsa.ed.lin.arr', t:'Array e lista dinâmica', min:30, pre:['dsa.fund.cx.amort'],
        saber:['custo de acesso, inserção no fim, inserção no meio e remoção','por que o redobramento dá O(1) amortizado'] },
      { id:'dsa.ed.lin.str', t:'String como estrutura', min:30, pre:['dsa.fund.js.str'],
        saber:['custo de substring, comparação e concatenação','quando converter para array de chars'] },
      { id:'dsa.ed.lin.ll', t:'Lista ligada simples', min:45,
        saber:['implementar inserção, remoção e busca','inverter uma lista in-place, iterativo e recursivo'] },
      { id:'dsa.ed.lin.dll', t:'Lista duplamente ligada e circular', min:30, pre:['dsa.ed.lin.ll'],
        nota:'A base de LRU cache, que é pergunta de entrevista clássica.',
        saber:['remover um nó em O(1) tendo só o ponteiro dele','usar sentinela para eliminar caso especial'] },
      { id:'dsa.ed.lin.stack', t:'Pilha', min:30,
        saber:['implementar com array e com lista ligada','citar 3 usos: parênteses, desfazer, DFS iterativo'] },
      { id:'dsa.ed.lin.queue', t:'Fila, deque e fila circular', min:45, pre:['dsa.ed.lin.stack','dsa.fund.js.kit'],
        nota:'Em JS, fila com shift() é O(n). Erro silencioso que derruba a solução em problema grande.',
        saber:['implementar fila O(1) com dois ponteiros ou lista ligada','saber por que array.shift() não serve'] },
    ]},

    { id:'dsa.ed.hash', t:'Estruturas associativas', filhos:[
      { id:'dsa.ed.hash.fn', t:'Função hash', min:30,
        saber:['o que faz uma boa função hash','por que distribuição uniforme importa'] },
      { id:'dsa.ed.hash.col', t:'Colisão: encadeamento e endereçamento aberto', min:45, pre:['dsa.ed.hash.fn'],
        saber:['descrever as duas estratégias','dizer o custo no pior caso de cada uma'] },
      { id:'dsa.ed.hash.load', t:'Fator de carga e redimensionamento', min:30, pre:['dsa.ed.hash.col'],
        saber:['por que O(1) é médio e não pior caso','o que dispara o rehash'] },
      { id:'dsa.ed.hash.set', t:'Set e contagem de frequência', min:30, pre:['dsa.ed.hash.fn'],
        nota:'O padrão que resolve mais problemas fáceis que qualquer outro.',
        saber:['montar mapa de frequência em uma passada','usar Set para deduplicar e para checar pertinência'] },
      { id:'dsa.ed.hash.ord', t:'O mapa ordenado que o JS não tem', min:30, pre:['dsa.ed.hash.load'],
        saber:['saber o que TreeMap/std::map dão e o JS não','contornar com array ordenado + busca binária, ou com heap'] },
    ]},

    { id:'dsa.ed.tree', t:'Árvores', filhos:[
      { id:'dsa.ed.tree.bin', t:'Árvore binária: vocabulário e forma', min:30,
        saber:['altura, profundidade, nível, folha, completa, cheia, balanceada'] },
      { id:'dsa.ed.tree.perc', t:'Percursos: pré, in, pós e por nível', min:45, pre:['dsa.ed.tree.bin'],
        nota:'Os quatro, recursivo e iterativo. Metade dos problemas de árvore é escolher o percurso certo.',
        saber:['os 3 em profundidade, recursivos, sem olhar','BFS por nível com fila','pelo menos um deles em versão iterativa'] },
      { id:'dsa.ed.tree.bst', t:'Árvore de busca binária', min:45, pre:['dsa.ed.tree.perc'],
        saber:['busca, inserção e remoção (os 3 casos da remoção)','por que o in-order de uma BST sai ordenado','pior caso O(n) quando degenera'] },
      { id:'dsa.ed.tree.bal', t:'Árvores balanceadas: AVL e rubro-negra', min:45, pre:['dsa.ed.tree.bst'],
        nota:'Conceito, não implementação. Ninguém pede AVL na entrevista; pedem saber por que existe.',
        saber:['explicar o que é rotação','dizer que garantia de altura O(log n) elas dão'] },
      { id:'dsa.ed.tree.heap', t:'Heap binário e fila de prioridade', min:60, pre:['dsa.ed.tree.bin','dsa.fund.js.kit'],
        saber:['propriedade de heap e representação em array','sift up e sift down','por que build-heap é O(n) e não O(n log n)'] },
      { id:'dsa.ed.tree.trie', t:'Trie (árvore de prefixos)', min:45, pre:['dsa.ed.hash.fn'],
        saber:['inserir, buscar e buscar por prefixo','custo em tempo e em memória vs hash'] },
      { id:'dsa.ed.tree.seg', t:'Segment tree e BIT — só o conceito', min:45, pre:['dsa.ed.tree.heap'],
        nota:'Raro em entrevista de produto. Saber que existe e para que serve basta.',
        saber:['dizer que problema resolvem (consulta em intervalo com atualização)','citar a complexidade'] },
    ]},

    { id:'dsa.ed.graph', t:'Grafos — a estrutura', filhos:[
      { id:'dsa.ed.graph.voc', t:'Vocabulário e classificação', min:30,
        saber:['dirigido, ponderado, cíclico, conexo, denso vs esparso','o que é grau, caminho e ciclo'] },
      { id:'dsa.ed.graph.rep', t:'Matriz vs lista de adjacência', min:30, pre:['dsa.ed.graph.voc'],
        saber:['custo de espaço e de "existe aresta?" nas duas','saber qual escolher por densidade'] },
      { id:'dsa.ed.graph.grid', t:'A matriz como grafo', min:30, pre:['dsa.ed.graph.rep'],
        nota:'Metade dos problemas de grafo em entrevista é uma grade disfarçada.',
        saber:['gerar vizinhos com vetor de direções','tratar borda e visitado sem duplicar código'] },
      { id:'dsa.ed.graph.dsu', t:'Union-Find (DSU)', min:45, pre:['dsa.ed.graph.voc','dsa.fund.js.kit'],
        saber:['find com compressão de caminho e union por rank','saber que dá quase O(1) amortizado','citar 2 problemas que ele resolve melhor que DFS'] },
    ]},
  ]},

  { id:'dsa.alg', t:'Algoritmos', nota:'Aqui a folha é sempre a mesma forma: entender a ideia, implementar sem olhar, saber o custo e quando usar.', filhos:[

    { id:'dsa.alg.ord', t:'Ordenação', filhos:[
      { id:'dsa.alg.ord.simp', t:'Bubble, selection e insertion sort', min:45,
        nota:'Não se usa nenhum. Se pergunta os três, e insertion é ótimo em array quase ordenado.',
        saber:['implementar os três','dizer melhor/médio/pior de cada','saber quais são estáveis'] },
      { id:'dsa.alg.ord.merge', t:'Merge sort', min:45, pre:['dsa.fund.cx.rec'],
        saber:['implementar do zero, sem olhar','justificar O(n log n) pela árvore de recorrência','por que é estável e por que precisa de O(n) extra'] },
      { id:'dsa.alg.ord.quick', t:'Quick sort: pivô e particionamento', min:60, pre:['dsa.alg.ord.merge'],
        saber:['implementar com Lomuto e entender Hoare','por que o pior caso é O(n²) e como o pivô aleatório evita','por que é in-place mas não estável'] },
      { id:'dsa.alg.ord.heap', t:'Heap sort', min:45, pre:['dsa.ed.tree.heap'],
        saber:['implementar usando build-heap','comparar com quick e merge em espaço e estabilidade'] },
      { id:'dsa.alg.ord.lin', t:'Ordenação não-comparativa: counting, radix, bucket', min:45, pre:['dsa.alg.ord.simp'],
        saber:['quando dá para bater O(n log n)','a premissa que cada uma exige da entrada'] },
      { id:'dsa.alg.ord.prop', t:'Estabilidade, in-place e o limite Ω(n log n)', min:30, pre:['dsa.alg.ord.quick'],
        saber:['provar o limite inferior por árvore de decisão','dizer por que estabilidade importa em ordenação por múltiplas chaves'] },
      { id:'dsa.alg.ord.js', t:'O sort do JS por dentro', min:20, pre:['dsa.fund.js.sort','dsa.alg.ord.prop'],
        saber:['saber que o V8 usa Timsort e que é estável','saber quando escrever o próprio em vez de usar o nativo'] },
    ]},

    { id:'dsa.alg.busca', t:'Busca', filhos:[
      { id:'dsa.alg.busca.lin', t:'Busca linear e quando ela basta', min:20,
        saber:['dizer em que caso linear ganha de binária na prática'] },
      { id:'dsa.alg.busca.bin', t:'Busca binária clássica', min:45, pre:['dsa.fund.cx.not'],
        nota:'Escrever sem bug de índice é mais raro do que parece. Fixe um template e nunca mude.',
        saber:['implementar sem off-by-one, com um template só','provar a invariante do laço','evitar overflow no cálculo do meio'] },
      { id:'dsa.alg.busca.lim', t:'Primeira e última ocorrência (lower/upper bound)', min:45, pre:['dsa.alg.busca.bin'],
        saber:['as duas variantes com o mesmo template','usar para contar ocorrências em O(log n)'] },
      { id:'dsa.alg.busca.rot', t:'Busca binária em array rotacionado', min:45, pre:['dsa.alg.busca.lim'],
        saber:['achar o ponto de rotação','decidir qual metade está ordenada a cada passo'] },
      { id:'dsa.alg.busca.resp', t:'Busca binária na resposta', min:60, pre:['dsa.alg.busca.lim'],
        nota:'O salto conceitual: buscar no espaço de respostas, não no array. Koko, capacidade de navio, etc.',
        saber:['reconhecer o padrão "menor X que satisfaz P"','escrever o predicado monotônico e provar a monotonicidade'] },
    ]},

    { id:'dsa.alg.rec', t:'Recursão e backtracking', filhos:[
      { id:'dsa.alg.rec.base', t:'Recursão: caso base e confiança recursiva', min:45, pre:['dsa.fund.js.pilha'],
        nota:'Parar de tentar rastrear a pilha inteira na cabeça é o que destrava recursão.',
        saber:['escrever 5 recursões assumindo que a chamada interna funciona','identificar caso base faltando'] },
      { id:'dsa.alg.rec.it', t:'Converter recursão em iteração', min:45, pre:['dsa.alg.rec.base'],
        saber:['DFS iterativo com pilha explícita','saber quando a conversão vale a pena'] },
      { id:'dsa.alg.rec.bt', t:'Backtracking: o template', min:60, pre:['dsa.alg.rec.base'],
        nota:'Escolher, recursar, desfazer. Um template só resolve subconjunto, permutação e combinação.',
        saber:['escrever o template escolher/recursar/desfazer','saber onde entra a poda'] },
      { id:'dsa.alg.rec.sub', t:'Subconjuntos, permutações e combinações', min:60, pre:['dsa.alg.rec.bt'],
        saber:['os três a partir do mesmo template','tratar duplicatas sem gerar repetido'] },
      { id:'dsa.alg.rec.poda', t:'Poda: transformar exponencial em viável', min:45, pre:['dsa.alg.rec.sub'],
        saber:['cortar ramo por limite e por inviabilidade','estimar o ganho da poda'] },
    ]},

    { id:'dsa.alg.graph', t:'Algoritmos em grafos', filhos:[
      { id:'dsa.alg.graph.bfs', t:'BFS e menor caminho não ponderado', min:60, pre:['dsa.ed.graph.rep','dsa.ed.lin.queue'],
        saber:['implementar com fila e visitados','processar por níveis quando a distância importa','por que BFS dá o menor caminho só sem peso'] },
      { id:'dsa.alg.graph.dfs', t:'DFS recursivo e iterativo', min:60, pre:['dsa.ed.graph.rep','dsa.alg.rec.it'],
        saber:['as duas versões','marcar visitado na hora certa para não repetir'] },
      { id:'dsa.alg.graph.comp', t:'Componentes conexas e flood fill', min:45, pre:['dsa.alg.graph.dfs','dsa.ed.graph.grid'],
        saber:['contar componentes','o padrão de ilhas em grade'] },
      { id:'dsa.alg.graph.ciclo', t:'Detecção de ciclo', min:45, pre:['dsa.alg.graph.dfs'],
        nota:'Em não-dirigido e em dirigido são algoritmos diferentes. Confundir os dois é erro comum.',
        saber:['ciclo em não-dirigido com pai','ciclo em dirigido com estado branco/cinza/preto'] },
      { id:'dsa.alg.graph.topo', t:'Ordenação topológica: Kahn e DFS', min:60, pre:['dsa.alg.graph.ciclo'],
        saber:['as duas abordagens','detectar que não existe ordem (há ciclo)','reconhecer o padrão de pré-requisito'] },
      { id:'dsa.alg.graph.dij', t:'Dijkstra', min:60, pre:['dsa.alg.graph.bfs','dsa.ed.tree.heap'],
        saber:['implementar com fila de prioridade','por que falha com peso negativo','a complexidade com heap'] },
      { id:'dsa.alg.graph.bf', t:'Bellman-Ford', min:45, pre:['dsa.alg.graph.dij'],
        saber:['aceitar peso negativo e detectar ciclo negativo','por que são V-1 iterações'] },
      { id:'dsa.alg.graph.fw', t:'Floyd-Warshall', min:45, pre:['dsa.alg.graph.bf'],
        saber:['todos-para-todos em O(V³)','quando compensa em vez de rodar Dijkstra V vezes'] },
      { id:'dsa.alg.graph.mst', t:'Árvore geradora mínima: Prim e Kruskal', min:60, pre:['dsa.ed.graph.dsu','dsa.alg.graph.dij'],
        saber:['as duas','por que Kruskal precisa de union-find','qual escolher por densidade'] },
    ]},

    { id:'dsa.alg.dp', t:'Programação dinâmica', nota:'O tema que mais reprova. A ordem aqui é deliberada: só chega em 2D depois de 1D estar automático.', filhos:[
      { id:'dsa.alg.dp.ideia', t:'Subestrutura ótima e subproblemas sobrepostos', min:45, pre:['dsa.alg.rec.base'],
        saber:['reconhecer as duas propriedades num problema novo','dizer por que sem elas não é DP'] },
      { id:'dsa.alg.dp.memo', t:'Memoização (top-down)', min:45, pre:['dsa.alg.dp.ideia'],
        nota:'Escreva a recursão burra primeiro, depois adicione o cache. Sempre nessa ordem.',
        saber:['transformar 3 recursões exponenciais em memoizadas','definir a chave do cache corretamente'] },
      { id:'dsa.alg.dp.tab', t:'Tabulação (bottom-up)', min:45, pre:['dsa.alg.dp.memo'],
        saber:['converter uma memoização em tabela','definir a ordem de preenchimento'] },
      { id:'dsa.alg.dp.1d', t:'DP em 1 dimensão', min:60, pre:['dsa.alg.dp.tab'],
        nota:'Escadas, house robber, coin change, word break, LIS.',
        saber:['escrever a recorrência antes do código, sempre','resolver 5 problemas 1D sem consultar'] },
      { id:'dsa.alg.dp.2d', t:'DP em 2 dimensões', min:60, pre:['dsa.alg.dp.1d'],
        nota:'LCS, edit distance, unique paths, knapsack.',
        saber:['montar a tabela e saber o que cada eixo significa','preencher a primeira linha e coluna corretamente'] },
      { id:'dsa.alg.dp.knap', t:'Knapsack e suas variantes', min:60, pre:['dsa.alg.dp.2d'],
        saber:['0/1, ilimitado e subset sum','reconhecer knapsack disfarçado'] },
      { id:'dsa.alg.dp.esp', t:'Otimização de espaço (rolling array)', min:45, pre:['dsa.alg.dp.2d'],
        saber:['reduzir 2D para 1D quando só a linha anterior importa','saber a direção certa de iteração ao fazer isso'] },
      { id:'dsa.alg.dp.rec', t:'Reconstruir a solução, não só o valor', min:45, pre:['dsa.alg.dp.2d'],
        saber:['guardar o caminho ou refazer por retrocesso na tabela'] },
      { id:'dsa.alg.dp.int', t:'DP em intervalos e em bitmask — conceito', min:45, pre:['dsa.alg.dp.knap'],
        saber:['reconhecer o formato','saber que existe e quando aparece'] },
    ]},

    { id:'dsa.alg.greedy', t:'Guloso', filhos:[
      { id:'dsa.alg.greedy.quando', t:'Quando guloso funciona (e como provar)', min:45, pre:['dsa.alg.dp.ideia'],
        nota:'A pergunta certa não é "qual a escolha gulosa", é "por que a escolha gulosa não perde".',
        saber:['enunciar a propriedade da escolha gulosa','dar um caso em que guloso falha e DP acerta'] },
      { id:'dsa.alg.greedy.int', t:'Intervalos: seleção de atividades e fusão', min:45, pre:['dsa.alg.greedy.quando'],
        saber:['ordenar pelo critério certo (fim, não início)','fundir intervalos sobrepostos em uma passada'] },
      { id:'dsa.alg.greedy.troca', t:'Troca de moedas: guloso vs DP', min:30, pre:['dsa.alg.greedy.quando','dsa.alg.dp.1d'],
        saber:['dizer para que conjuntos de moedas o guloso é correto'] },
      { id:'dsa.alg.greedy.huff', t:'Huffman — conceito', min:30, pre:['dsa.ed.tree.heap'],
        saber:['a ideia da construção com heap','por que produz código de prefixo ótimo'] },
    ]},
  ]},

  { id:'dsa.pad', t:'Padrões de entrevista', nota:'A camada que o NeetCode organiza. Cada padrão: reconhecer pelo enunciado, aplicar o template, saber o custo.', filhos:[
    { id:'dsa.pad.freq', t:'Mapa de frequência e contagem', min:30, pre:['dsa.ed.hash.set'],
      saber:['reconhecer pelo enunciado','resolver anagrama, duplicata e top-K de contagem'] },
    { id:'dsa.pad.2p', t:'Dois ponteiros', min:45, pre:['dsa.ed.lin.arr'],
      saber:['as duas formas: extremidades convergindo e ponteiro lento/rápido','saber que quase sempre exige entrada ordenada'] },
    { id:'dsa.pad.fs', t:'Ponteiro lento e rápido (ciclo)', min:45, pre:['dsa.pad.2p','dsa.ed.lin.ll'],
      saber:['detectar ciclo em lista','achar o início do ciclo (Floyd)','achar o meio da lista'] },
    { id:'dsa.pad.win', t:'Janela deslizante fixa e variável', min:60, pre:['dsa.pad.freq'],
      nota:'O padrão com melhor retorno por hora de estudo: transforma O(n²) em O(n) em dezenas de problemas.',
      saber:['o template de expandir/contrair','saber quando a janela é fixa e quando é variável','combinar com mapa de frequência'] },
    { id:'dsa.pad.pref', t:'Soma de prefixo e diferença', min:45, pre:['dsa.ed.lin.arr'],
      saber:['consulta de soma em intervalo em O(1)','prefixo com hash para subarray de soma alvo'] },
    { id:'dsa.pad.mono', t:'Pilha monotônica', min:60, pre:['dsa.ed.lin.stack'],
      nota:'Próximo maior elemento, temperaturas, maior retângulo. Difícil de reconhecer, mecânico depois de reconhecido.',
      saber:['o template crescente e o decrescente','reconhecer pelo "próximo maior/menor"'] },
    { id:'dsa.pad.topk', t:'Top-K com heap', min:45, pre:['dsa.ed.tree.heap'],
      saber:['por que heap de tamanho K bate ordenar tudo','escolher min-heap ou max-heap corretamente'] },
    { id:'dsa.pad.int', t:'Intervalos', min:45, pre:['dsa.alg.greedy.int'],
      saber:['inserir, fundir, contar sobreposição','o truque de varredura por eventos'] },
    { id:'dsa.pad.bit', t:'Manipulação de bits', min:45, pre:['dsa.fund.js.num'],
      saber:['AND/OR/XOR/shift e as identidades do XOR','contar bits, ligar/desligar/testar bit','a armadilha dos 32 bits em JS'] },
    { id:'dsa.pad.mat', t:'Matriz: rotação, espiral, marcação in-place', min:45, pre:['dsa.ed.graph.grid'],
      saber:['rotacionar 90° in-place','percorrer em espiral sem caso especial'] },
    { id:'dsa.pad.math', t:'Matemática e geometria de entrevista', min:45,
      saber:['MDC, primos, potência rápida','overflow e divisão inteira em JS'] },
    { id:'dsa.pad.desg', t:'Problemas de projeto (LRU, Twitter, mediana em fluxo)', min:60, pre:['dsa.ed.lin.dll','dsa.pad.topk'],
      nota:'A ponte para system design: combinar duas estruturas para bater a complexidade pedida.',
      saber:['LRU com hash + lista dupla','mediana com dois heaps'] },
  ]},

  { id:'dsa.prat', t:'Prática deliberada', nota:'Como resolver, não o que resolver. É o que faz 150 problemas virarem competência em vez de histórico.', filhos:[
    { id:'dsa.prat.met', t:'Método para atacar um problema novo', min:45,
      nota:'Entender → exemplos → força bruta → otimizar → codar → testar. Nessa ordem, sempre.',
      saber:['enunciar as 6 etapas','aplicar num problema do zero sem pular para o código'] },
    { id:'dsa.prat.20', t:'A regra dos 20 minutos', min:20, pre:['dsa.prat.met'],
      nota:'Tentar antes de ver a resposta é o que fixa. Ver antes de tentar é assistir alguém malhar.',
      saber:['sustentar 20min sem olhar','depois de olhar, fechar tudo e reimplementar do zero'] },
    { id:'dsa.prat.teste', t:'Testar sem rodar: casos de borda', min:45, pre:['dsa.prat.met'],
      saber:['listar vazio, um elemento, todos iguais, negativos, estouro','percorrer o código à mão com um caso'] },
    { id:'dsa.prat.rev', t:'Revisão espaçada 3/7/21', min:20, pre:['dsa.prat.20'],
      nota:'Substitui a planilha que você não vai manter. Problema resolvido volta em 3, 7 e 21 dias.',
      saber:['reimplementar um problema antigo sem consultar','marcar o que falhou para voltar antes'] },
    { id:'dsa.prat.voz', t:'Pensar em voz alta, em inglês', min:45, pre:['dsa.prat.met','dsa.fund.js.kit'],
      nota:'Cruza com a trilha de inglês. Entrevista técnica internacional cobra as duas ao mesmo tempo.',
      saber:['narrar a solução enquanto escreve','anunciar a complexidade antes de codar'] },
    { id:'dsa.prat.mock', t:'Simulado cronometrado', min:60, pre:['dsa.prat.voz'],
      saber:['2 problemas em 45min, falando em inglês','sem consultar nada'] },
  ]},
]};
