/**
 * Inglês — do C2 passivo ao C2 ativo, com IELTS 7.0 no caminho.
 *
 * A árvore ignora leitura e listening de propósito: você já entende tudo.
 * Todo tema aqui é PRODUÇÃO — o que você não consegue fazer sair, e o que
 * um examinador de banda 7 procura e hoje não encontra.
 */
import type { Trilha } from './types';

export const INGLES: Trilha = {
  id: 'en', t: 'Inglês — produção', tipos: ['en_write', 'en_speak', 'en_tutor'], cor: '--chart-1', marco: 'ielts', fecha: false,
  nota: 'Compreensão está pronta. O trabalho inteiro é output: escrever, falar, e ser corrigido.',
  filhos: [

  { id:'en.diag', t:'Diagnóstico e critério', nota:'Antes de treinar, saber onde você está e como isso é medido.', filhos:[
    { id:'en.diag.base', t:'Linha de base gravada e escrita', min:30,
      nota:'A referência contra a qual você vai comparar daqui a um ano.',
      saber:['gravou 5min falando sobre um tema livre, sem editar','escreveu 250 palavras cronometradas em 40min','arquivou os dois com a data'] },
    { id:'en.diag.desc', t:'Descritores de banda do IELTS', min:40,
      nota:'Os quatro critérios que decidem sua nota. Sem isso você treina no escuro.',
      saber:['citar os 4 critérios de Writing e de Speaking','dizer o que separa banda 6 de banda 7 em cada um','apontar em qual critério a SUA linha de base cai'] },
    { id:'en.diag.erros', t:'Inventário dos seus erros recorrentes', min:40, pre:['en.diag.base'],
      nota:'Erro de brasileiro é previsível. O seu tem nome e é um conjunto pequeno.',
      saber:['listou os 10 erros que mais repete','classificou cada um em gramática, léxico ou pronúncia','virou os 10 em cards'] },
  ]},

  { id:'en.w', t:'Escrita', tipos:['en_write'], nota:'Quatro sessões por semana. É onde a banda 7 se ganha ou se perde.', filhos:[

    { id:'en.w.frase', t:'Mecânica da frase', nota:'O nível onde o português vaza sem você perceber.', filhos:[
      { id:'en.w.frase.ordem', t:'Ordem de palavras e ênfase', min:20,
        saber:['explicar por que o inglês fixa SVO e o português não','reescrever 5 frases suas movendo a ênfase sem quebrar a ordem'] },
      { id:'en.w.frase.art', t:'Artigos: a / an / the / zero', min:20,
        nota:'O erro nº1 de brasileiro em texto acadêmico — e o mais fácil de corrigir.',
        saber:['dizer as 4 regras de uso do zero article','corrigir 10 frases suas sem consultar'] },
      { id:'en.w.frase.tempo', t:'Present perfect vs past simple', min:20,
        nota:'Não existe equivalente em português. Por isso você erra por padrão.',
        saber:['explicar a diferença por relevância presente, não por tempo decorrido','escolher certo em 10 frases seguidas'] },
      { id:'en.w.frase.tempos2', t:'Os outros tempos que importam', min:20, pre:['en.w.frase.tempo'],
        nota:'Past perfect, future forms, used to / would.',
        saber:['usar past perfect só quando há duas ações passadas ordenadas','distinguir will, going to e present continuous para futuro'] },
      { id:'en.w.frase.cond', t:'Condicionais e hipóteses', min:20,
        saber:['produzir os tipos 0, 1, 2 e 3 sem pensar','usar mixed conditional numa frase própria'] },
      { id:'en.w.frase.rel', t:'Orações relativas (defining vs non-defining)', min:20,
        saber:['explicar por que a vírgula muda o sentido','escrever 5 frases longas com relativa encaixada, corretas'] },
      { id:'en.w.frase.sub', t:'Subordinação: concessiva, causal, final', min:20, pre:['en.w.frase.rel'],
        nota:'Although, whereas, so that, in order to. É o que dá cara de banda 7 ao parágrafo.',
        saber:['juntar duas frases curtas suas em uma complexa, 5 vezes','usar whereas para contraste sem virar but'] },
      { id:'en.w.frase.pass', t:'Voz passiva: quando serve, quando é ruído', min:20,
        saber:['dizer os 3 casos em que a passiva é a escolha certa','reescrever 5 passivas ruins suas em ativa'] },
      { id:'en.w.frase.cont', t:'Contáveis, incontáveis e quantificadores', min:20,
        saber:['acertar much/many, few/little, amount/number em 10 frases','listar 10 incontáveis que em português são contáveis'] },
      { id:'en.w.frase.prep', t:'Preposições dependentes', min:20,
        nota:'depend ON, interested IN, responsible FOR. Não há lógica — há lista e uso.',
        saber:['ter 30 pares verbo+preposição em cards','usar 10 deles em texto próprio sem consultar'] },
      { id:'en.w.frase.pont', t:'Pontuação inglesa', min:20,
        nota:'Vírgula, ponto e vírgula e travessão seguem regras diferentes do português.',
        saber:['usar ponto e vírgula corretamente 3 vezes','parar de usar vírgula onde o inglês pede ponto (comma splice)'] },
      { id:'en.w.frase.par', t:'Paralelismo e concordância', min:20,
        saber:['corrigir 5 listas não paralelas','resolver concordância com sujeitos compostos e coletivos'] },
    ]},

    { id:'en.w.lex', t:'Vocabulário e registro', nota:'Lexical Resource é um quarto da nota — e é onde C2 passivo mais engana.', filhos:[
      { id:'en.w.lex.col', t:'Colocações: make, do, take, have, give', min:20,
        nota:'Saber a palavra e não saber com quem ela anda é o que soa traduzido.',
        saber:['produzir 30 colocações corretas de cabeça','corrigir 10 colocações erradas suas'] },
      { id:'en.w.lex.col2', t:'Colocações acadêmicas e de negócio', min:20, pre:['en.w.lex.col'],
        saber:['usar 20 colocações do tipo "conduct research", "meet a deadline", "raise a concern"'] },
      { id:'en.w.lex.prec', t:'Precisão: sinônimos que não são sinônimos', min:20,
        nota:'Trocar palavra por sinônimo de dicionário derruba a banda em vez de subir.',
        saber:['diferenciar 10 pares próximos (say/tell, make/cause, big/large/great)','justificar cada escolha por contexto'] },
      { id:'en.w.lex.hedge', t:'Hedging e cautela acadêmica', min:20,
        nota:'May, tend to, arguably, it appears that. Afirmação absoluta soa amadora em texto acadêmico.',
        saber:['suavizar 10 afirmações categóricas suas','saber quando NÃO suavizar'] },
      { id:'en.w.lex.reg', t:'Registro: acadêmico, profissional, informal', min:20,
        saber:['reescrever o mesmo parágrafo nos três registros','listar 15 palavras que não podem aparecer em Task 2'] },
      { id:'en.w.lex.phr', t:'Phrasal verbs por frequência', min:20,
        nota:'Os 100 mais comuns cobrem quase tudo. E quase nenhum cabe em Task 2.',
        saber:['usar 20 phrasal verbs em fala natural','saber o equivalente formal de cada um para a escrita'] },
      { id:'en.w.lex.falso', t:'Falsos cognatos e traduções armadilha', min:20,
        saber:['listar 25 falsos cognatos PT→EN que você já usou errado','usar o termo correto de cada um em frase'] },
      { id:'en.w.lex.nom', t:'Nominalização', min:20, pre:['en.w.lex.reg'],
        nota:'"The government decided" vira "the government\u2019s decision". Sobe o registro; em excesso, mata o texto.',
        saber:['nominalizar 5 frases suas','reverter 5 nominalizações pesadas de outro texto'] },
      { id:'en.w.lex.tec', t:'Léxico técnico da sua área em inglês', min:20,
        nota:'Você lê isso todo dia e nunca produziu. Deploy, rollback, trade-off, edge case.',
        saber:['explicar 15 termos técnicos em inglês, com suas palavras','sem recorrer ao termo em português'] },
    ]},

    { id:'en.w.coe', t:'Coesão e organização', nota:'Coherence and Cohesion — o critério que brasileiro perde por excesso, não por falta.', filhos:[
      { id:'en.w.coe.par', t:'O parágrafo: topic sentence, desenvolvimento, fecho', min:20,
        saber:['escrever 3 parágrafos com topic sentence explícita','apontar a topic sentence em qualquer parágrafo alheio'] },
      { id:'en.w.coe.link', t:'Conectivos sem mecanicidade', min:20, pre:['en.w.coe.par'],
        nota:'"Firstly, secondly, in conclusion" em toda redação é sinal de banda 6, não 7.',
        saber:['reescrever um texto seu trocando conectivos óbvios por referência e substituição','usar however, nevertheless e nonetheless com a diferença certa'] },
      { id:'en.w.coe.ref', t:'Referência, substituição e elipse', min:20, pre:['en.w.coe.link'],
        nota:'A coesão de verdade: pronome, "this approach", "the former", omissão.',
        saber:['eliminar 5 repetições de um texto seu sem usar sinônimo forçado'] },
      { id:'en.w.coe.flu', t:'Fluxo de informação: dado → novo', min:20, pre:['en.w.coe.ref'],
        saber:['reordenar 5 frases para que cada uma comece pelo que já foi dito'] },
    ]},

    { id:'en.w.gen', t:'Gêneros de texto', nota:'Cada um tem forma fixa. Forma decorada libera atenção para a língua.', filhos:[
      { id:'en.w.gen.op', t:'Ensaio de opinião (agree/disagree)', min:40, pre:['en.w.coe.par'],
        saber:['estrutura de 4 parágrafos de memória','tese inequívoca na introdução','escreveu um completo em 40min'] },
      { id:'en.w.gen.disc', t:'Ensaio de discussão (both views)', min:40, pre:['en.w.gen.op'],
        saber:['dar peso equilibrado aos dois lados e ainda assim ter posição no fim'] },
      { id:'en.w.gen.prob', t:'Problema e solução', min:40, pre:['en.w.gen.op'],
        saber:['casar cada solução com o problema correspondente, sem sobra'] },
      { id:'en.w.gen.vant', t:'Vantagens e desvantagens', min:40, pre:['en.w.gen.op'],
        saber:['responder se as vantagens superam, quando a pergunta pedir'] },
      { id:'en.w.gen.two', t:'Two-part question', min:40, pre:['en.w.gen.op'],
        saber:['responder as DUAS perguntas — o erro clássico é responder uma'] },
      { id:'en.w.gen.t1l', t:'Task 1 — gráfico de linha e de barra', min:40,
        nota:'Descrever tendência, não opinar. Overview obrigatório.',
        saber:['escrever overview com as 2 tendências principais','usar 10 verbos de tendência com o advérbio certo'] },
      { id:'en.w.gen.t1p', t:'Task 1 — pizza, tabela e gráficos múltiplos', min:40, pre:['en.w.gen.t1l'],
        saber:['comparar proporções sem listar todos os números','selecionar o que é relevante'] },
      { id:'en.w.gen.t1proc', t:'Task 1 — processo e mapa', min:40, pre:['en.w.gen.t1l'],
        nota:'Muda tudo: passiva, sequência, sem números.',
        saber:['descrever um processo de 7 etapas com conectivos de sequência','descrever mudança em mapa com linguagem de localização'] },
      { id:'en.w.gen.mail', t:'E-mail profissional em inglês', min:20,
        saber:['escrever pedido, recusa e follow-up, cada um em 5 linhas','acertar abertura e fecho por nível de formalidade'] },
      { id:'en.w.gen.tec', t:'Escrita técnica: PR, issue, README, doc', min:20, pre:['en.w.lex.tec'],
        nota:'É a escrita que o emprego remoto internacional realmente cobra.',
        saber:['escrever uma PR description com contexto, mudança e risco','escrever um README de projeto seu, em inglês'] },
      { id:'en.w.gen.async', t:'Comunicação assíncrona: Slack, standup escrito', min:20, pre:['en.w.gen.tec'],
        saber:['reportar um bloqueio em 3 linhas, sem rodeio e sem grosseria'] },
      { id:'en.w.gen.ps', t:'Personal statement / carta de motivação', min:40, pre:['en.w.gen.op'],
        nota:'Peça obrigatória da aplicação para o nível 9. Vale um marco inteiro.',
        saber:['rascunho completo com motivo, trajetória e encaixe com o curso'] },
      { id:'en.w.gen.cl', t:'Cover letter e resumo de LinkedIn', min:20, pre:['en.w.gen.ps'],
        saber:['uma cover letter de 4 parágrafos','um "About" de LinkedIn em 5 linhas, em inglês'] },
    ]},

    { id:'en.w.rev', t:'Revisão e correção', nota:'Sem correção, escrever muito só automatiza o erro.', filhos:[
      { id:'en.w.rev.self', t:'Auto-revisão com checklist próprio', min:20, pre:['en.diag.erros'],
        saber:['revisar um texto seu procurando SÓ os seus 10 erros','achar pelo menos 3 antes de rodar o corretor'] },
      { id:'en.w.rev.tool', t:'Usar corretor sem terceirizar o aprendizado', min:20, pre:['en.w.rev.self'],
        nota:'Aceitar sugestão sem entender é o modo mais rápido de não aprender nada.',
        saber:['explicar POR QUE cada correção aceita estava errada','rejeitar pelo menos uma sugestão com justificativa'] },
      { id:'en.w.rev.card', t:'Transformar erro em card que funciona', min:20, pre:['en.w.rev.tool'],
        nota:'Card com a frase errada e a certa lado a lado não ensina. Card cloze com contexto ensina.',
        saber:['formatar 5 cards no formato cloze com contexto','nenhum card com resposta óbvia pelo formato'] },
      { id:'en.w.rev.tutor', t:'Levar escrita para o tutor', min:20, pre:['en.w.rev.card'],
        nota:'Para banda 7 em Writing você precisa de correção humana. Uma sessão de tutor em cada quatro vira correção de texto.',
        saber:['enviou texto antes da sessão','saiu da sessão com 3 correções que o corretor automático não pegou'] },
    ]},
  ]},

  { id:'en.s', t:'Fala', nota:'Sua barreira é vergonha, não conhecimento. A árvore trata as duas coisas separadamente.', filhos:[

    { id:'en.s.pron', t:'Pronúncia', tipos:['en_speak'], nota:'Não é sotaque — é inteligibilidade. Banda 7 exige ser entendido sem esforço.', filhos:[
      { id:'en.s.pron.voc', t:'Vogais que o português não tem', min:20,
        nota:'/ɪ/ vs /iː/ (ship/sheep), /æ/ (cat), schwa /ə/.',
        saber:['produzir os 3 pares mínimos mais críticos','ouvir a própria gravação e identificar qual saiu errada'] },
      { id:'en.s.pron.th', t:'Os sons /θ/ e /ð/', min:20,
        saber:['pronunciar think e this sem virar "f" ou "d"','sustentar numa frase inteira'] },
      { id:'en.s.pron.fim', t:'Consoantes finais e encontros consonantais', min:20,
        nota:'O "i" fantasma: "hot-chi dog". É o traço mais audível de brasileiro.',
        saber:['dizer 10 palavras terminadas em consoante sem vogal de apoio','sustentar em fala corrida'] },
      { id:'en.s.pron.word', t:'Acento tônico da palavra', min:20,
        saber:['acertar a sílaba tônica de 20 palavras longas','saber que o acento muda entre substantivo e verbo (REcord/reCORD)'] },
      { id:'en.s.pron.sent', t:'Acento da frase e ritmo', min:20, pre:['en.s.pron.word'],
        nota:'Inglês é stress-timed, português é syllable-timed. Isso importa mais que qualquer fonema isolado.',
        saber:['reduzir palavras funcionais a schwa numa frase longa','manter o intervalo entre tônicas constante'] },
      { id:'en.s.pron.ent', t:'Entonação: pergunta, lista, contraste', min:20, pre:['en.s.pron.sent'],
        saber:['distinguir pergunta genuína de retórica pela curva','usar entonação de contraste conscientemente'] },
      { id:'en.s.pron.conn', t:'Connected speech: linking, elisão, contração', min:20, pre:['en.s.pron.sent'],
        nota:'Por que você entende podcast e não entende conversa: ninguém fala palavra por palavra.',
        saber:['produzir 10 ligações naturais (an apple, want to → wanna)','usar contrações sem soar informal demais'] },
    ]},

    { id:'en.s.flu', t:'Fluência', tipos:['en_speak'], nota:'Falar sem travar. Treinado sozinho, sem plateia — que é o que remove a vergonha.', filhos:[
      { id:'en.s.flu.shad', t:'Shadowing: método e progressão', min:20,
        saber:['acompanhar 1min de áudio nativo com atraso de meia frase','fazer 3 passadas com foco diferente: som, ritmo, entonação'] },
      { id:'en.s.flu.mono', t:'Monólogo cronometrado', min:20, pre:['en.s.flu.shad'],
        saber:['falar 5min sobre tema sorteado sem trocar para português','ouvir a gravação e anotar 2 pontos'] },
      { id:'en.s.flu.pause', t:'Pausa e preenchimento natural', min:20, pre:['en.s.flu.mono'],
        nota:'Silêncio pensado soa melhor que "ééé". Nativos usam well, I mean, actually.',
        saber:['usar 5 fillers naturais','substituir o "ééé" por pausa em 2min de fala'] },
      { id:'en.s.flu.par', t:'Paráfrase: falar sem a palavra que faltou', min:20, pre:['en.s.flu.pause'],
        nota:'A habilidade que mais separa quem trava de quem não trava.',
        saber:['descrever 10 objetos sem usar o nome deles','nunca parar a frase por falta de palavra'] },
      { id:'en.s.flu.corr', t:'Auto-correção sem travar', min:20, pre:['en.s.flu.par'],
        saber:['corrigir um erro no meio da frase e seguir, sem reiniciar'] },
      { id:'en.s.flu.vel', t:'Velocidade e clareza', min:20, pre:['en.s.flu.corr'],
        saber:['sustentar ritmo constante por 3min','desacelerar de propósito num ponto importante'] },
    ]},

    { id:'en.s.int', t:'Interação', tipos:['en_tutor'], nota:'Falar sozinho é metade. A outra metade só existe com outra pessoa — é o bloco do tutor.', filhos:[
      { id:'en.s.int.turn', t:'Tomar e ceder turno', min:20,
        saber:['entrar numa fala sem ser rude, 3 formas diferentes','devolver a palavra explicitamente'] },
      { id:'en.s.int.dis', t:'Discordar educadamente', min:20, pre:['en.s.int.turn'],
        saber:['discordar em 3 níveis de força','discordar da ideia sem atacar a pessoa'] },
      { id:'en.s.int.clar', t:'Pedir esclarecimento sem perder a cara', min:20,
        nota:'"Sorry, could you rephrase that?" salva mais entrevista que vocabulário avançado.',
        saber:['pedir repetição de 3 formas','confirmar entendimento parafraseando'] },
      { id:'en.s.int.small', t:'Small talk profissional', min:20,
        saber:['abrir e fechar conversa curta','ter 3 tópicos seguros prontos'] },
      { id:'en.s.int.meet', t:'Reunião: propor, interromper, resumir', min:20, pre:['en.s.int.dis'],
        nota:'É a habilidade que o emprego remoto internacional cobra na primeira semana.',
        saber:['fazer uma proposta com justificativa em 30s','resumir o que foi decidido ao fim'] },
    ]},

    { id:'en.s.ielts', t:'IELTS Speaking', tipos:['en_speak','en_tutor'], nota:'Formato fixo. Decorado, ele deixa de consumir atenção.', filhos:[
      { id:'en.s.ielts.p1', t:'Part 1 — perguntas pessoais', min:20, pre:['en.diag.desc'],
        saber:['responder em 2–3 frases, nunca monossílabo','estender com razão ou exemplo sem enrolar'] },
      { id:'en.s.ielts.p2', t:'Part 2 — cue card, 1min prep + 2min fala', min:40, pre:['en.s.ielts.p1'],
        saber:['estruturar a anotação de 1min sempre igual','falar 2min completos sem parar'] },
      { id:'en.s.ielts.p3', t:'Part 3 — discussão abstrata', min:40, pre:['en.s.ielts.p2'],
        nota:'É aqui que a banda 7 se decide: opinião fundamentada sobre tema geral.',
        saber:['sustentar posição com 2 razões e 1 exemplo','considerar o contra-argumento sem perder a posição'] },
    ]},

    { id:'en.s.job', t:'Inglês de entrevista', tipos:['en_speak','en_tutor'], nota:'Liga a trilha de inglês com a de carreira. As duas cobram a mesma coisa.', filhos:[
      { id:'en.s.job.star', t:'STAR em inglês', min:20, pre:['en.s.flu.mono'],
        saber:['contar uma história de trabalho em 2min no formato STAR','sem pular o Resultado, que é o que todo mundo pula'] },
      { id:'en.s.job.code', t:'Explicar código e arquitetura em voz alta', min:20, pre:['en.w.lex.tec'],
        nota:'Entrevista técnica é pensar falando. Em inglês, é duas coisas ao mesmo tempo.',
        saber:['narrar a própria solução enquanto escreve','explicar um trade-off sem travar'] },
      { id:'en.s.job.beh', t:'Banco de perguntas comportamentais', min:20, pre:['en.s.job.star'],
        saber:['ter 8 histórias STAR gravadas cobrindo conflito, falha, liderança e prazo'] },
      { id:'en.s.job.ask', t:'Perguntar ao entrevistador', min:20,
        saber:['ter 6 perguntas boas sobre time, processo e expectativa'] },
      { id:'en.s.job.neg', t:'Negociação de proposta em inglês', min:20, pre:['en.s.job.beh'],
        saber:['pedir faixa sem dar número primeiro','recusar e contrapor sem fechar a porta'] },
    ]},
  ]},

  { id:'en.ex', t:'Exame', tipos:['en_write','en_speak'], nota:'A fase final: forma, cronômetro e logística.', filhos:[
    { id:'en.ex.form', t:'Formato completo e gestão de tempo', min:40, pre:['en.w.gen.t1proc','en.s.ielts.p3'],
      saber:['saber a duração de cada seção de cabeça','ter um plano de minutagem para Task 1 e Task 2'] },
    { id:'en.ex.sim1', t:'Simulado completo nº1', min:60, pre:['en.ex.form'],
      saber:['fez as 4 seções cronometradas, em uma sentada','estimou a própria banda com os descritores'] },
    { id:'en.ex.gap', t:'Análise do simulado e plano de correção', min:40, pre:['en.ex.sim1'],
      saber:['identificou o critério mais fraco','definiu 3 semanas de foco nele'] },
    { id:'en.ex.sim2', t:'Simulados nº2 a nº4', min:60, pre:['en.ex.gap'],
      saber:['tendência de banda estável ou subindo','Writing dentro do tempo, sem correria no final'] },
    { id:'en.ex.log', t:'Inscrição e logística da prova', min:20, pre:['en.ex.sim2'],
      nota:'Escolher entre Academic (é este) e o centro; conferir prazo do TRF para as aplicações.',
      saber:['data marcada','documento de identificação conferido','prazo do resultado bate com o prazo das escolas'] },
  ]},
]};
